//! `dpl preload` — per-site opcache preload control.
//!
//! A preloaded site runs on its own php-fpm master with `opcache.preload` set, so
//! its script's code is compiled into shared memory once at master start and the
//! first request is warm. Preloaded entries are frozen for the master's life, so
//! the scaffold `generate` writes targets vendor/framework, not app code.

use std::path::PathBuf;

use anyhow::Result;
use dpl_core::ipc::{Request, Response, SiteInfo};

use crate::daemon;

/// The default scaffold filename, also the default `dpl preload on` script.
const SCRIPT_NAME: &str = "dpl-preload.php";

/// `dpl preload` / `dpl preload status` — one row per site.
pub fn status(home: Option<&str>, json: bool) -> Result<()> {
    let sites = list_sites(home)?;
    let sites: Vec<&SiteInfo> = sites.iter().filter(|s| s.source != "proxy").collect();

    if json {
        let rows: Vec<serde_json::Value> = sites
            .iter()
            .map(|s| {
                serde_json::json!({
                    "name": s.name,
                    "php": s.php,
                    "preload": s.preload,
                })
            })
            .collect();
        println!("{}", serde_json::to_string_pretty(&serde_json::json!({ "sites": rows }))?);
        return Ok(());
    }

    if sites.is_empty() {
        println!("No local sites yet. Link a project with `dpl link .`.");
        return Ok(());
    }

    let width = sites.iter().map(|s| s.name.len()).max().unwrap_or(4).max(4);
    println!("{:<width$}  {:<8}  PRELOAD", "SITE", "PHP", width = width);
    for s in &sites {
        println!(
            "{:<width$}  {:<8}  {}",
            s.name,
            s.php.as_deref().unwrap_or("default"),
            s.preload.as_deref().unwrap_or("off"),
            width = width
        );
    }
    if sites.iter().any(|s| s.preload.is_some()) {
        println!(
            "\nPreloaded code is frozen until the master restarts — run `dpl reload` after \
             changing a preloaded file (or its vendor tree)."
        );
    } else {
        println!("\nScaffold a script with `dpl preload generate <site>`, then `dpl preload on <site>`.");
    }
    Ok(())
}

/// `dpl preload generate [site]` — scaffold a vendor-first preload script.
pub fn generate(home: Option<&str>, site: Option<String>) -> Result<()> {
    let dir = project_dir(home, site)?;
    let target = dir.join(SCRIPT_NAME);
    if target.exists() {
        anyhow::bail!(
            "{} already exists — edit it, or delete it first to regenerate.",
            target.display()
        );
    }
    std::fs::write(&target, SCAFFOLD)?;
    println!("Wrote {}.", target.display());
    println!("Review the globs (it preloads vendor/, not app/), then `dpl preload on <site>`.");
    Ok(())
}

/// `dpl preload on|off <site>`.
pub fn set(home: Option<&str>, site: String, script: Option<String>) -> Result<()> {
    send(home, Request::SetPreload { site: site.to_lowercase(), script })
}

fn list_sites(home: Option<&str>) -> Result<Vec<SiteInfo>> {
    let Response::Sites { sites, .. } = daemon::call(Request::ListSites, home)? else {
        anyhow::bail!("unexpected daemon response");
    };
    Ok(sites)
}

/// The project directory for a site name, or the current directory when omitted.
fn project_dir(home: Option<&str>, site: Option<String>) -> Result<PathBuf> {
    match site {
        Some(name) => {
            let name = name.to_lowercase();
            let s = list_sites(home)?
                .into_iter()
                .find(|s| s.name == name)
                .ok_or_else(|| anyhow::anyhow!("no local site named {name}. See `dpl preload`."))?;
            Ok(PathBuf::from(s.path))
        }
        None => std::env::current_dir().map_err(Into::into),
    }
}

fn send(home: Option<&str>, request: Request) -> Result<()> {
    match daemon::call(request, home)? {
        Response::Message { text } => {
            println!("{text}");
            Ok(())
        }
        Response::Ok => Ok(()),
        other => crate::commands::unexpected(other),
    }
}

/// Starter preload script. Vendor-first, app excluded, with the frozen-code
/// caveat up front. The user owns and tunes it — `opcache.preload` is finicky
/// about memory and dependency order, so dpl scaffolds rather than guesses.
const SCAFFOLD: &str = r#"<?php
/**
 * dpl opcache preload script (generated by `dpl preload generate`).
 *
 * php-fpm runs this ONCE at master start; everything it compiles lives in shared
 * memory for every worker, for the master's life. That is what makes the first
 * request warm — but preloaded files are FROZEN: edits do not take effect until
 * the master restarts (`dpl reload`). So preload STABLE code (vendor / framework),
 * NOT the app code you are actively editing.
 *
 * Tune the globs below to your project, then run `dpl preload on <site>`.
 */

$root = __DIR__;
$autoload = $root . '/vendor/autoload.php';
if (!is_file($autoload)) {
    fwrite(STDERR, "dpl preload: no vendor/autoload.php — run composer install\n");
    return;
}
require $autoload;

/** Compile every .php under $dir into opcache WITHOUT executing it. */
$compile = static function (string $dir): void {
    if (!is_dir($dir)) {
        return;
    }
    $it = new RecursiveIteratorIterator(
        new RecursiveDirectoryIterator($dir, FilesystemIterator::SKIP_DOTS)
    );
    foreach ($it as $file) {
        if ($file->getExtension() === 'php') {
            // opcache_compile_file warns on classes whose parents are not yet
            // loaded; that is harmless for preload, so silence it.
            @opcache_compile_file($file->getPathname());
        }
    }
};

// Vendor is large and rarely changes — ideal to preload. If 256MB of opcache is
// not enough, narrow this to the packages that dominate your boot.
$compile($root . '/vendor');

// App code changes on every save; preloading it means your edits will not apply
// until the master restarts. Off by default — uncomment only if you accept that.
// $compile($root . '/app');
"#;
